### ISSUE TITLE
PyPi package does not work with TF-GPU-2.0.0-alpha0

### ISSUE THREAD

**Issue by ralphbrooks** [kpe/bert-for-tf2#1]
KPE,

Just saw your post re BERT for TF 2.0. Looks interesting but I am already stuck out of the gate. Thought you might be able to help.

I have the following issue (with error messages):

```
pip install --user tensorflow-gpu==2.0.0-alpha0
pip install --user bert-for-tf2
Collecting bert-for-tf2
  Downloading https://files.pythonhosted.org/packages/29/71/0ed46e4c3f8791d0b86e7283474bb20549e16d1445d5fba5205c984
145cf/bert-for-tf2-0.1.5.tar.gz
Collecting tensorflow>=1.13.99 (from bert-for-tf2)
  Could not find a version that satisfies the requirement tensorflow>=1.13.99 (from bert-for-tf2) (from versions: 1
.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 2.0.0a0)
No matching distribution found for tensorflow>=1.13.99 (from bert-for-tf2)
```

In short, I am getting the error even though it looks like TF 2.0 is installed. Proof of installation is as follows:

```
ralph_a_brooks@main-keras-p4-instance:~$ python
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-alpha0'
```

Any thoughts as to what is going wrong?

Best,

Ralph

**Comment by kpe** [comment]
I guess the `tensorflow` dependency in my `requirements.txt` is sub-optimal.
I've just removed it, and released a new 0.1.6 version, so you should be able to install it now, after installing `tensorflow` or `tensorflow-gpu` first.

**Comment by kpe** [comment]
**N.B.** It turns out one should use `2.0.0a0` and not `2.0.0-alpha0`, i.e. `tensorflow[-gpu]-2.0.0a0` and not `tensorflow[-gpu]-2.0.0-alpha0` (s. https://stackoverflow.com/questions/55521403/pip-cant-find-tensorflow-gpu-2-0-alpha).

**Comment by ralphbrooks** [comment]
Thanks. I got it to load. 

As a side note, bert-for-tf2 wants to install tf 1.13.1. The only way that I could get this to work was to load bert-for-tf2 first and then to load tf 2.0.0a0 (as seen below)>

```
pip install --user bert-for-tf2 # Still need to get this to work
pip install --user tensorflow-gpu==2.0.0a0
```
