### ISSUE TITLE
Fine Tune Layer Possible Error in Examples

### ISSUE THREAD

**Issue by luischinchillagarcia** [kpe/bert-for-tf2#15]
When creating the fine-tuning layers, I notice we only take the first element of the second dimension in the bert layer. The bert layer's dimensions are [batch_size, token_id, bert_embedding_dims], meaning the Lambda operation below (which is shown in both the GPU and TPU examples), is just taking the first token to do any learning under a classification task. Is this an error? Or perhaps I am misinterpreting the layer architecture here.

```
  input_ids = keras.layers.Input(shape=(max_seq_len,), dtype='int32', name="input_ids")
  output = bert(input_ids)
  cls_out = keras.layers.Lambda(lambda seq: seq[:, 0, :])(output)
```

**Comment by kpe** [comment]
@luischinchillagarcia - taking only the first token representation, i.e. the one corresponding to the `[CLS]` token is the standard when doing sequence classification with BERT (check the paper). Note that a special `[CLS]` token gets prepended when feeding data to BERT.

However, you are free to try if `MaxPooling` or `AveragePooling` (as shown in the tpu example notebook) on the whole sequence output works better for your model/data.

**Comment by luischinchillagarcia** [comment]
Perfect! Thank you for your response!
