### ISSUE TITLE
Constructor with Params not working

### ISSUE THREAD

**Issue by negedng** [kpe/bert-for-tf2#16]
Hi!

The BertModelLayer constructor expects 0 params (only self):
TypeError: __init__() takes 1 positional argument but 2 were given

The example at the Readme uses BertModelLayer(BertModelLayer.Params(...)) for original bert params, but it's not working.

**Comment by kpe** [comment]
@negedng - thank you for catching this, I just fixed it in the README, it should be:
```
BertModelLayer(**BertModelLayer.Params(...))
```

i.e. passing kargs to the BertModelLayer constructor.
