### ISSUE TITLE
"training" parameter missing?

### ISSUE THREAD

**Issue by jonathanbratt** [kpe/bert-for-tf2#18]
https://github.com/kpe/bert-for-tf2/blob/cad915ee9d20802a05181373fe30b716a70bc870/bert/transformer.py#L177

In the `call` method of the `SingleTransformerEncoderLayer` class, when the `ProjectionLayer` object is being called, shouldn't the `training` parameter be passed along?

**Comment by kpe** [comment]
@jonathanbratt - first, thank you for your message!
I believe however, that those parameters, i.e. `training` and `mask` does not have to be passed manually. It's kind of Keras black magic happening behind the scenes :-) (... like it is so often the case in keras)
If you know a case, where this is not set properly, let me know! 
(This might for example be the case, if you call your layer directly - but as long keras is doing the call, keras will try to find the proper `kargs` for the `call()`)
