### ISSUE TITLE
albert tokenization

### ISSUE THREAD

**Issue by mshlis** [kpe/bert-for-tf2#19]
using your albert code, it does not generate a `vocab.txt` file, but under assets there is a `*.vocab` file similar to those used in spm.   

Given that in the network the weight shape for is (30000, ...) and not (30522, ...) im unsure if for proper alignment i should use berts vocab.txt but delete the empty space or use spm. Either way, you should probably update the documentation to incorporate this.

**Comment by kpe** [comment]
@mshlis - thank you for your message! Which albert code exactly are you referring to? 
Please note, while the google's bert pre-trained models use a vocab_size of 30522 and a custom tokenizer, the albert pre-trained models from tfhub use a vocab_size of 30000 and sentencepice as tokenizer. 

So, when using some of the pre-trained albert models, the model input should be prepared/tokenized differently. 

It seems, I currently have no example of how tokenization should be best done for albert, so I'll have to add one! Thank you for noticing this!

**Comment by kpe** [comment]
I have recently replaced the `bert/tokenization.py` with `bert/tokenization/bert_tokenization.py` and `bert/tokenization/albert_tokenization.py` and will soon add some sample code in the README.
