### ISSUE TITLE
load pretrained model weights problems

### ISSUE THREAD

**Issue by Christnow** [kpe/bert-for-tf2#20]
model_name = "albert_base"
model_dir = bert.fetch_brightmart_albert_model(model_name, ".models")
model_ckpt = os.path.join(model_dir, "albert_model.ckpt")
bert_params = bert.params_from_pretrained_ckpt(model_dir)
l_bert = bert.BertModelLayer.from_params(bert_params)
bert.load_bert_weights(l_bert, model_ckpt)      # should be called after model.build()

problems:
     179 def bert_prefix(bert: BertModelLayer):
    180     re_bert = re.compile(r'(.*)/(embeddings|encoder)/(.+):0')
--> 181     match = re_bert.match(bert.weights[0].name)
    182     assert match, "Unexpected bert layer: {} weight:{}".format(bert, bert.weights[0].name)
    183     prefix = match.group(1)
IndexError: list index out of range

what should i do?

**Comment by kpe** [comment]
@Christnow - take a note of the comment on the last line:
```python
bert.load_bert_weights(l_bert, model_ckpt) # should be called after model.build()
```
i.e. you can load the weights, only after the weights have been instantiated in the keras model. This is only possible once the shape of the input is known. So usually, this would be done by calling `Model.build()` in Keras. You could only explicitly do a dummy call to your layer, which would also instantiate the weights:

```python
l_bert(tf.zeros(1, 128)) 
bert.load_bert_weights(l_bert, model_ckpt)  
```
a minimal example with `Model.build()` would be:
```python
model = tf.keras.models.Sequential([l_bert])
model.build((1,128))
l_bert.load_bert_weights(l_bert, model_ckpt)
```
