### ISSUE TITLE
load bert chinese pretrained model problems

### ISSUE THREAD

**Issue by Christnow** [kpe/bert-for-tf2#21]
model_name = "chinese_L-12_H-768_A-12.zip"
model_dir = bert.fetch_google_bert_model(model_name,'models')
model_ckpt = os.path.join(model_dir, "bert_model.ckpt")

bert_params = bert.params_from_pretrained_ckpt(model_dir)
l_bert = bert.BertModelLayer.from_params(bert_params, name="bert")

# use in Keras Model here, and call model.build()

bert.load_bert_weights(l_bert, model_ckpt)      # should be called after model.build()

problems:

NotFoundError: models/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12.zip; No such file or directory

what should i do

**Comment by kpe** [comment]
@Christnow - this is a bug (there should be no `.zip` suffix in the `model_name`). Thank you for spotting it!
I'll do a release fixing it, right away. For now, just try something like:
```python
model_dir = bert.fetch_google_bert_model(model_name,'models')
model_dir = model_dir.replace(".zip", "")
model_ckpt = os.path.join(model_dir, "bert_model.ckpt")
```
