### ISSUE TITLE
what's the difference between load_stock_weight, load_bert_weight and load_albert_weight?

### ISSUE THREAD

**Issue by fancyerii** [kpe/bert-for-tf2#22]
As the name suggested, load_bert_weight and load_albert_weight are used to load bert and albert weights, But what's load_stock_weight mean?

**Comment by kpe** [comment]
@fancyerii - `load_stock_weights` is a synonym and the old/deprecated name for `load_bert_weights`. Both of them are the same method. I have initially used the name `load_stock_weights` but only later realized that it is not a good name (it is still there for compatibility, and I will remove it at some point).
