### ISSUE TITLE
Exception with TFLiteConverter convert method call

### ISSUE THREAD

**Issue by bill3code** [kpe/bert-for-tf2#24]
``` Python
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from bert import BertModelLayer, params_from_pretrained_ckpt, load_bert_weights
from tensorflow.compat.v2.lite import TFLiteConverter

bert_params = params_from_pretrained_ckpt(folder)
l_bert = BertModelLayer.from_params(bert_params, name="bert")

max_seq_len = 512
l_input_ids = Input(shape=(max_seq_len,), dtype='int32')
l_token_type_ids = Input(shape=(max_seq_len,), dtype='int32')

output = l_bert([l_input_ids, l_token_type_ids])

model = Model(inputs=[l_input_ids, l_token_type_ids], outputs=output)
model.build(input_shape=[(None, max_seq_len), (None, max_seq_len)])

load_bert_weights(l_bert, checkpoint_path)

converter = TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
```
<pre>
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, op_dict, producer_op_list)
    500         results = c_api.TF_GraphImportGraphDefWithResults(
--> 501             graph._c_graph, serialized, options)  # pylint: disable=protected-access
    502         results = c_api_util.ScopedTFImportGraphDefResults(results)

InvalidArgumentError: Input 0 of node model_6/bert/embeddings/word_embeddings/embedding_lookup was passed float from model_6/bert/embeddings/word_embeddings/embedding_lookup/Read/ReadVariableOp/resource:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-31-330d0f1c4d51> in <module>
     21 
     22 converter = TFLiteConverter.from_keras_model(model)
---> 23 tflite_model = converter.convert()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py in convert(self)
    403 
    404     frozen_func = _convert_to_constants.convert_variables_to_constants_v2(
--> 405         self._funcs[0], lower_control_flow=False)
    406     input_tensors = [
    407         tensor for tensor in frozen_func.inputs

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py in convert_variables_to_constants_v2(func, lower_control_flow)
    573   output_graph_def.versions.CopyFrom(graph_def.versions)
    574   return _construct_concrete_function(func, output_graph_def,
--> 575                                       converted_input_indices)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py in _construct_concrete_function(func, output_graph_def, converted_input_indices)
    369   new_func = wrap_function.function_from_graph_def(output_graph_def,
    370                                                    new_input_names,
--> 371                                                    new_output_names)
    372 
    373   # Manually propagate shape for input tensors where the shape is not correctly

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py in function_from_graph_def(graph_def, inputs, outputs)
    618     importer.import_graph_def(graph_def, name="")
    619 
--> 620   wrapped_import = wrap_function(_imports_graph_def, [])
    621   import_graph = wrapped_import.graph
    622   return wrapped_import.prune(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py in wrap_function(fn, signature, name)
    596           signature=signature,
    597           add_control_dependencies=False,
--> 598           collections={}),
    599       variable_holder=holder,
    600       signature=signature)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py in __call__(self, *args, **kwargs)
     81 
     82   def __call__(self, *args, **kwargs):
---> 83     return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
     84 
     85   def call_with_variable_creator_scope(self, fn):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py in wrapped(*args, **kwargs)
     87     def wrapped(*args, **kwargs):
     88       with variable_scope.variable_creator_scope(self.variable_creator_scope):
---> 89         return fn(*args, **kwargs)
     90 
     91     return wrapped

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py in _imports_graph_def()
    616 
    617   def _imports_graph_def():
--> 618     importer.import_graph_def(graph_def, name="")
    619 
    620   wrapped_import = wrap_function(_imports_graph_def, [])

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    403       name=name,
    404       op_dict=op_dict,
--> 405       producer_op_list=producer_op_list)
    406 
    407 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, op_dict, producer_op_list)
    503       except errors.InvalidArgumentError as e:
    504         # Convert to ValueError for backwards compatibility.
--> 505         raise ValueError(str(e))
    506 
    507     # Create _DefinedFunctions for any imported functions.

ValueError: Input 0 of node model_6/bert/embeddings/word_embeddings/embedding_lookup was passed float from model_6/bert/embeddings/word_embeddings/embedding_lookup/Read/ReadVariableOp/resource:0 incompatible with expected resource.
</pre>

**Comment by kpe** [comment]
I guess the embedding_lookup operation is not yet supported by TFLight - https://www.tensorflow.org/lite/guide/ops_compatibility#tensorflow_lite_operations 
Have you also tried the tf-nightly?

**Comment by kpe** [comment]
@bill3code - indeed your code above seems work with tf-nightly.
