### ISSUE TITLE
Switched multi-output prediction arrays 

### ISSUE THREAD

**Issue by roebius** [kpe/bert-for-tf2#27]
Hello @kpe,
first of all, thank you for sharing your very useful repos.

Using bert-for-tf2 for a QA task I created a model with 4 outputs.
For the model creation I specify the outputs as a dictionary with keys in this order: 
"_id_", "_start_", "_end_", "_type_".
When predicting I would expect the predictions output as a list of arrays in the same order:
[_id, start, end, type_] 
but I receive instead a list in the following order:
[_type, end, start, id_]
(actually, "_end_" and "_start_" have the same shape so I am not sure about their relative positions).

Is this "position-switching" of the output arrays a normal behavior or could it be an issue with bert-for-tf2?

Thank you

**Comment by kpe** [comment]
@roebius - this is most likely an issue with keras and dict outputs - internally in tf.keras the dict is flattened to a list, and the order might get changed. I thought until now that the order in this case is alphabetical (and would be interested to understand why that's not the case - I believe it is different between TF versions; I also have issued a different but related bug to the TF team - https://github.com/tensorflow/tensorflow/issues/34199).
I don't think it is an issue with bert-for-tf2. I guess you are using `BertModelLayer` which is just a layer (not aware of the "outer" keras model populating the outputs). You could easily replace it with an `EmbeddingLayer` and see, if the keras behavior will  change.

**Comment by kpe** [comment]
@roebius - I believe it is name of the output tensor that counts not the dictionary entry :-)
I'm using a:
```
ident = lambda n: tf.keras.layers.Lambda(lambda a: a, name=n)
outputs = [ident("output-a")(out_a), ident("output-b")(out_b)]
```
to force the names on the output tensors.

**Comment by roebius** [comment]
Thank you for your reply and suggestions.
I confirm I am using `BertModelLayer`. I also believe it is a Keras issue, but it is a bit complicated for me to change the output layer names: some TF ops I am using force name prefixes for the output layers, so I have to use the actual layer names for my losses but I have to use different names for the TFRecords I am feeding.

![pooler_transform](https://user-images.githubusercontent.com/8594073/70952248-f1e00e80-2065-11ea-9665-a0affd6881a9.png)

**Comment by kpe** [comment]
@roebius - changing the output names can be done with the `ident` function/layer above. But if I remember correctly it is relevant for the model losses only.

**Comment by roebius** [comment]
I was eventually able to solve the issue.
For the model creation, I am passing the outputs as a list instead of a dictionary: this way the prediction outputs are not switched anymore.

Thanks to your `ident` suggestion I was able to refactor my code in order to use the output layer names consistently between model output, model losses and TFRecord feature mapping when feeding the model for fit/predict.
Many thanks again.
