### ISSUE TITLE
Can't freeze pre-trained params  

### ISSUE THREAD

**Issue by fakerbrother** [kpe/bert-for-tf2#29]
Thanks for releasing this repo, but I met a problem. I can.t freeze pre-trained params, I use  the following code to frezze params, but it did't work. 
`model_dir = "D:/ProgramData/Pre_Traines_Model_Of_Bert/chinese_L-12_H-768_A-12"

    bert_params = bert.params_from_pretrained_ckpt(model_dir)
    l_bert = bert.BertModelLayer.from_params(bert_params, name="bert")
    l_bert.apply_adapter_freeze()
    max_seq_len = 128
    l_input_ids = keras.layers.Input(shape=(max_seq_len,), dtype='int32')
    # l_token_type_ids = keras.layers.Input(shape=(max_seq_len,), dtype='int32')

    # using the default token_type/segment id 0
    output = l_bert(l_input_ids)  # output: [batch_size, max_seq_len, hidden_size]
    model = keras.Model(inputs=l_input_ids, outputs=output)
    model.build(input_shape=(None, max_seq_len))
    bert.loader.load_stock_weights(l_bert, os.path.join(model_dir, "bert_model.ckpt"))
    model.summary()`
And I get following result:
 
![1576581406(1)](https://user-images.githubusercontent.com/42272100/70991917-7cc31680-2103-11ea-8bf4-e05c88cb9e01.png)
As you see, all params are trainable, Could u help me ASAP, THX! :)

**Comment by kpe** [comment]
@fakerbrother - try calling the `apply_adapter_freeze()` only after `model.build()` as before `build()` the parameter shapes are in general unknown (and therefore could get instantiated by keras only after `build()` or a similar operation providing the input shapes).

**Comment by fakerbrother** [comment]
ok，I will try it, thanks for your response, :)

**Comment by ck37** [comment]
I also see no effect from calling `apply_adapter_freeze()` after `model.build()`. Here is example code:

```python
model_name = "uncased_L-12_H-768_A-12"
model_dir = bert.fetch_google_bert_model(model_name, ".models")
model_ckpt = os.path.join(model_dir, "bert_model.ckpt")

bert_params = bert.params_from_pretrained_ckpt(model_dir)
l_bert = bert.BertModelLayer.from_params(bert_params, name="bert")

max_seq_len = 128
l_input_ids      = keras.layers.Input(shape=(max_seq_len,), dtype='int32')
l_token_type_ids = keras.layers.Input(shape=(max_seq_len,), dtype='int32')

# using the default token_type/segment id 0
output = l_bert(l_input_ids)                              # output: [batch_size, max_seq_len, hidden_size]

output = layers.Dense(64, activation = 'relu')(output)
output = Dropout(0.4)(output)
output = Dense(1, activation = "linear")(output)

model = keras.Model(inputs = l_input_ids, outputs = output)

model.build(input_shape = (None, max_seq_len))

# Needs to be after model.build().
l_bert.apply_adapter_freeze()

bert.load_bert_weights(l_bert, model_ckpt)      # should be called after model.build()

opt_adam = tf.keras.optimizers.Adam()

model.compile(loss = tf.keras.losses.MeanSquaredError(), optimizer = opt_adam)
model.summary()
```

![image](https://user-images.githubusercontent.com/50770/76152760-6ed4c000-6078-11ea-9c4d-1507497c09a1.png)

**Comment by ptamas88** [comment]
you may set it with l_bert.trainable = False. but it's just a wild guess, I Don't know what apply_adapter_freeze() function does.

**Comment by kpe** [comment]
@ck37 - ``apply_adapter_freeze()`` is used together with the ``adapter_size`` parameter, i.e. it will freeze all but the adapter layers for training; in the case you use plan bert (i.e. without adapter layers), the method will not have an effect.


To freeze your layers, you might use the standard keras mechanisms:
```
l_bert.trainable = False
```

just like @ptamas88  says!
