### ISSUE TITLE
Could you update some examples using bert-for-tf2?

### ISSUE THREAD

**Issue by LeeJump** [kpe/bert-for-tf2#3]

**Comment by erikvaningen** [comment]
+1 for this request. 

It would be great to have this integrated in the 
_Predicting Movie Reviews with BERT on TF Hub_  example.

**Comment by kpe** [comment]
@erikvaningen - I've just committed a (quick'n'dirty) notebook, showing how to train Movie Reviews classifier on a GPU in colab. Take a look under [examples](/kpe/bert-for-tf2/examples/ 	movie_reviews_with_bert_for_tf2_on_gpu.ipynb).

**Comment by LeeJump** [comment]
Thank you sincerely. 



------------------ 原始邮件 ------------------
发件人: "kpe"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 晚上7:05
收件人: "kpe/bert-for-tf2"<bert-for-tf2@noreply.github.com>; 
抄送: "-"<5403517@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kpe/bert-for-tf2] Could you update some examples usingbert-for-tf2? (#3)




@erikvaningen - I've just committed a (quick'n'dirty) notebook, showing how to train Movie Reviews classifier on a GPU in colab. Take a look under [examples](/kpe/bert-for-tf2/examples/ 	movie_reviews_with_bert_for_tf2_on_gpu.ipynb).
