### ISSUE TITLE
Word Vectors and Sentence Vectors

### ISSUE THREAD

**Issue by muhammadfahid51** [kpe/bert-for-tf2#31]
Ok. I got it how to use a pre-trained model. But I was looking for how do I get the word vectors and also the doctovec property of Bert ?

**Comment by DUTANGx** [comment]
> Ok. I got it how to use a pre-trained model. But I was looking for how do I get the word vectors and also the doctovec property of Bert ?

The output is in shape (Batch-size, Max-length, Hidden_model). say you have a sentence with real length N, normally we use output[0, 0, :] as the embedding for your input sequence, while outputs[0, 1:N+1, :] are the embeddings for your input tokens.

**Comment by kpe** [comment]
@muhammadfahid51 - for the "doctovec" property of BERT one usually simply takes the BERT output corresponding to the `[CLS]` token (see the examples). This however only makes sense when you fine-tune your BERT layer on the task of interest. As an alternative you could freeze the BERT weights, and feed the BERT token representations in a followup model. I'm not aware of any outstanding benefits of the later approach however.
