### ISSUE TITLE
bert_custom model

### ISSUE THREAD

**Issue by muhammadfahid51** [kpe/bert-for-tf2#34]
Hi there, 
Any idea how to use a Convolution Network or LSTM for sentiment Analysis using bert-for-tf2 embeddings. Will I have to replace Lambda layer or any other method

**Comment by kpe** [comment]
@muhammadfahid51 - should we discuss this in #33 - where you already have an example of a CNN on top of bert?

**Comment by kpe** [comment]
duplicates #33
