### ISSUE TITLE
bert-pretrain

### ISSUE THREAD

**Issue by muhammadfahid51** [kpe/bert-for-tf2#36]
Hi,
How can I pre-train bert using bert-for-tf2. 
We need,
input_ids, mask_ids and segment_ids. 
Once we prepare that and making vocab as well as config, How to proceed with bert-for-tf2.

**Comment by kpe** [comment]
@muhammadfahid51  - Currently bert-for-tf2 does not have an example or tools for pre-training from scratch. When pre-training from scratch it might be easier using the workflow from the original google-research/bert. Once you have the pre-trained weights, you could fine-tune with bert-for-tf2.

**Comment by muhammadfahid51** [comment]
Yeah I got it. Will you add it ?

**Comment by kpe** [comment]
yes, I'll be adding support for pre-training from scratch or continuing pre-training as part of #13 (but it might take some time).
Closing for now, and handling this in #13.
