### ISSUE TITLE
Load Google's official Chinese ALBERT model

### ISSUE THREAD

**Issue by hankcs** [kpe/bert-for-tf2#37]
Hi, I'm trying to load the newly released official Chinese models from Google. These models aren't in tfhub format so I have to load them through `load_stock_weights`.  However, `load_stock_weights` seems to be wrote for brightmart's version, of which `map_to_stock_variable_name` returns wrong names. Interestingly, `map_to_tfhub_albert_variable_name` makes correct guess.

**Comment by kpe** [comment]
@hankcs - are you referring to the BERT weights (i.e. https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip or https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip)?

If you have problems loading the weights, could you please post the exact source code you are using here, or check with the `README.md`, i.e.:
```
model_name = "chinese_L-12_H-768_A-12"
model_dir = bert.fetch_google_bert_model(model_name, ".models")
model_ckpt = os.path.join(model_dir, "bert_model.ckpt")

bert_params = bert.params_from_pretrained_ckpt(model_dir)
l_bert = bert.BertModelLayer.from_params(bert_params, name="bert")

# use in Keras Model here, and call model.build()

bert.load_bert_weights(l_bert, model_ckpt)
```

**Comment by kpe** [comment]
reopening - I guess it is about the https://github.com/google-research/ALBERT weights, i.e.  https://storage.googleapis.com/albert_models/albert_base_zh.tar.gz

**Comment by kpe** [comment]
@hankcs - loading of the official Google ALBERT weights should now be possible - 
```
model_name = "albert_base_v2"
model_dir    = bert.fetch_google_albert_model(model_name, ".models")
model_ckpt   = os.path.join(albert_dir, "model.ckpt-best")

model_params = bert.albert_params(model_dir)
l_bert = bert.BertModelLayer.from_params(model_params, name="albert")

# use in Keras Model here, and call model.build()

bert.load_albert_weights(l_bert, model_ckpt)      # should be called after model.build()
```

**Comment by hankcs** [comment]
Yes, thank you.
