### ISSUE TITLE
tf.logging does not exists in TF 2.0

### ISSUE THREAD

**Issue by Bidek56** [kpe/bert-for-tf2#39]
tf.logging was removed from TF 2.0 but albert_tokenization.py has few instances of tf.logging, I suggest changing it to tf.compat.v1.logging or replacing it with absl-py as per docs.

**Comment by kpe** [comment]
fixed with 032eda1abd998cf07fd978057b8a491db04e1d41 by importing compat.v1 (i.e. merging from google-research/ALBERT).
