### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'logging'

### ISSUE THREAD

**Issue by hankcs** [kpe/bert-for-tf2#47]
I think tf.logging is gone and we need to remove all tf.logging.

```
python3.6/site-packages/bert/tokenization/albert_tokenization.py", line 242, in __init__
    tf.logging.info("loading sentence piece model")
AttributeError: module 'tensorflow' has no attribute 'logging'
```

**Comment by IamJeffG** [comment]
I am not sure that this was ever a bug, until the proposed fix 707816d broke it.

In `albert_tokenization.py`, the `tf` alias already refers to `tensorflow.compat.v1`:

https://github.com/kpe/bert-for-tf2/blob/55f6a6fd5d8ea14f96ee19938b7a1bf0cb26aaea/bert/tokenization/albert_tokenization.py#L28


So when we write `tf.compat.v1.logging.info(...)` that gets resolved to `tensorflow.compat.v1.compat.v1.logging.info(...)` which, of course, does not exist:

https://github.com/kpe/bert-for-tf2/blob/55f6a6fd5d8ea14f96ee19938b7a1bf0cb26aaea/bert/tokenization/albert_tokenization.py#L242

```pytb
  File "/opt/conda/lib/python3.7/site-packages/bert/tokenization/albert_tokenization.py", line 242, in __init__
    tf.compat.v1.logging.info("loading sentence piece model")
AttributeError: module 'tensorflow_core.compat.v1.compat' has no attribute 'v1'
```

If I instead install a very old version, `bert-for-tf2==0.13.2` — the version before 707816d — then I can use `bert.albert_tokenization` with no problem.
