### ISSUE TITLE
get error when predict

### ISSUE THREAD

**Issue by breadbread1984** [kpe/bert-for-tf2#5]
I load pretrained chinese model and predict semantic similarity. then I get the following error message

>  File "Predictor.py", line 154, in _classify
    outputs = self.bert(inputs, mask, training);
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 753, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 905, in _run_internal_graph
    assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("bert/Identity:0", shape=(None, 128, 768), dtype=float32)

I am using tensorflow-beta1. I load pretrained bert with the following code.

```python
#!/usr/bin/python3

import os;
import tensorflow as tf;
from bert import BertModelLayer;
from bert.loader import StockBertConfig, load_stock_weights;
from bert.tokenization import FullTokenizer;

def flatten_layers(root_layer):
    if isinstance(root_layer, tf.keras.layers.Layer):
        yield root_layer
    for layer in root_layer._layers:
        for sub_layer in flatten_layers(layer):
            yield sub_layer

def freeze_bert_layers(l_bert):
    """
    Freezes all but LayerNorm and adapter layers - see arXiv:1902.00751.
    """
    for layer in flatten_layers(l_bert):
        if layer.name in ["LayerNorm", "adapter-down", "adapter-up"]:
            layer.trainable = True
        elif len(layer._layers) == 0:
            layer.trainable = False
        l_bert.embeddings_layer.trainable = False

def BERT(max_seq_len = 128, bert_model_dir = 'models/chinese_L-12_H-768_A-12', do_lower_case = False):

    # load bert parameters
    with tf.io.gfile.GFile(os.path.join(bert_model_dir, "bert_config.json"), "r") as reader:
        stock_params = StockBertConfig.from_json_string(reader.read());
        bert_params = stock_params.to_bert_model_layer_params();
    # create bert structure according to the parameters
    bert = BertModelLayer.from_params(bert_params, name = "bert");
    # inputs
    input_token_ids = tf.keras.Input((max_seq_len,), dtype = tf.int32, name = 'input_ids');
    input_segment_ids = tf.keras.Input((max_seq_len,), dtype = tf.int32, name = 'token_type_ids');
    # outputs
    output = bert([input_token_ids, input_segment_ids]);
    # create model containing only bert layer
    model = tf.keras.Model(inputs = [input_token_ids, input_segment_ids], outputs = output);
    model.build(input_shape = [(None, max_seq_len), (None, max_seq_len)]);
    # freeze_bert_layers
    freeze_bert_layers(bert);
    # load bert layer weights
    load_stock_weights(bert, os.path.join(bert_model_dir, "bert_model.ckpt"));
    # create tokenizer, chinese character needs no lower case.
    tokenizer = FullTokenizer(vocab_file = os.path.join(bert_model_dir, "vocab.txt"), do_lower_case = do_lower_case);
    return model, tokenizer;
```

**Comment by kpe** [comment]
@breadbread1984 Your code above looks OK to me (keep in mind the `freeze_bert_layers` will not freeze the `LayerNorm` layers, which is needed for adapter-BERT). 
How do you call `model.predict`?

**Comment by breadbread1984** [comment]
I just tokenize the input string pair and feed into bert.
my code is [here](https://github.com/breadbread1984/QASystem/blob/3338b1f02dd0d3e26aa502e8419a537a37c23d9d/Predictor.py#L177)

**Comment by kpe** [comment]
@breadbread1984 - I think, it doesn't work because, there is no `Model` in your `_classify` function. Keras needs a Model instance to wire the tf graph. You have `build` a `model()` in `BERT.py`, but you have your classifier (dropout and dense layers) in `_classify` - and they are not yet wired into the execution graph. For this you either need a separate Model calling the bert-Model, or as an alternative, you can return the bert layer from BERT.py, and build a single classifier model in your `_classify` (i.e. model.build() in Predictor only). Does this explanation make sense?

**Comment by breadbread1984** [comment]
got it. thx for your informative and kindly reply!
