### ISSUE TITLE
Installation issues for tensorflow-gpu

### ISSUE THREAD

**Issue by Inevitable-Marzipan** [kpe/bert-for-tf2#6]
I was trying to set up a new conda environment to use this package. I want to use tensorflow with gpu support so I first run `pip install tensorflow-gpu==1.14`. Running `tensorflow.test.is_gpu_available()` returns True and all works.

I then run `pip install bert-for-tf2` and in the process of installing the requirements, params-flow has a requirement of tensorflow, so tensorflow==1.14 gets installed at this time. Now when running 'tensorflow.test.is_gpu_available()` False is returned. Both tensorflow and tensorflow-gpu are in the conda environment.

I'm not sure what is the proper way to deal with this inconsistency, but the way I got around it was to first install tensorflow-gpu. Then clone the repo for params-flow, remove tensorflow from it's requirements and then install with `python setup.py install` from within the repo. Finally bert-for-tf2 can be installed with pip and all seems to work. 

EDIT: 

Just read one of the closed issues, and things seem to work if bert-for-tf2 is installed first and then a gpu version of tensorflow is installed afterwards.

**Comment by kpe** [comment]
@Inevitable-Marzipan - thank you for your observation! I now also removed the `tensorflow` requirement from `params-flow`. This should allow to install the `tensorflow` or `tensorflow-gpu` first, and `bert-for-tf2` afterwards.
