### ISSUE TITLE
use custom vocab.txt

### ISSUE THREAD

**Issue by 2696120622** [kpe/bert-for-tf2#66]
My corpous consists of pure numbers like 1, 2, ..., 1000000, ..., 1002342, ....
It is differen from words in any language.
Can I replace the vocab.txt with my own vocab.tx created using my corpous for fine-tuning bert?
Or, should I train bert on my corpous from scratch?

Thanks.

**Comment by kpe** [comment]
pre-training from scratch would always work.
To use a pre-trained model you have to use the exact same tokenizer that the pre-trained model uses.
