### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by AndreFWeber** [kpe/bert-for-tf2#69]
I am using it in my project and it works flawlessly. The thing is that I happen to call my python script from a PHP script and listen to the stdout for debugging purposes. I noticed that there are some prints in your code that my PHP script is reading. 

With that said, would you consider adding a verbose flag on your code, please?

for example, I am receiving the output of these prints, from loader.py:

    print("Done loading {} BERT weights from: {} into {} (prefix:{}). "
          "Count of weights not found in the checkpoint was: [{}]. "
          "Count of weights with mismatched shape: [{}]".format(
              len(weight_value_tuples), ckpt_path, bert, prefix, skip_count, len(skipped_weight_value_tuples)))

    print("Unused weights from checkpoint:",
          "\n\t" + "\n\t".join(sorted(stock_weights.difference(loaded_weights))))

**Comment by kpe** [comment]
@AndreFWeber - sorry, for the late reply. Would an env variable work for you?

**Comment by AndreFWeber** [comment]
Yes, it would work as well. Thanks, I appreciate it.

**Comment by rajeshkinf** [comment]
hi @AndreFWeber , did this work for you? I get the following error as we cannot set 

```
    os.environ['VERBOSE'] = 0
  File "/home/ec2-user/anaconda3/lib/python3.8/os.py", line 680, in __setitem__
    value = self.encodevalue(value)
  File "/home/ec2-user/anaconda3/lib/python3.8/os.py", line 750, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int

```
as per bert-for-tf2/bert/loader.py
```
_verbose = os.environ.get('VERBOSE', 1)  # verbose print per default
trace = print if int(_verbose) else lambda *a, **k: None
```
