### ISSUE TITLE
will albert for tf2 be released?

### ISSUE THREAD

**Issue by breadbread1984** [kpe/bert-for-tf2#7]
will albert for tf2 be released?

**Comment by kpe** [comment]
I have not yet evaluate exactly how much effort it would be to load some of the released albert weights, but I'm planning to do so soon. Until recently there were no pre-trained models for English, but I believe they might be released soon (according to https://github.com/brightmart/albert_zh?source=post_page-----df8f7b58fa28----------------------#%E5%8F%91%E5%B8%83%E8%AE%A1%E5%88%92-release-plan), so it would be worth evaluating.

**Comment by breadbread1984** [comment]
please, thx

**Comment by kpe** [comment]
I added some initial support for the ALBERT model through the `shared_layer=True` and the `embedding_size` parameters. However no support for loading of the released pre-trained weights yet.

**Comment by breadbread1984** [comment]
thx for your speedy support of the new model!

**Comment by kpe** [comment]
with the latest commit bert-for-tf2 supports now loading of the pre-trained ALBERT weights released by @brightmart. I very much hope there we'll be pre-trained weights for English too soon, see also brightmart/albert_zh#11

**Comment by brightmart** [comment]
great job!  
@kpe @breadbread1984

**Comment by breadbread1984** [comment]
@kpe you are great! @brightmart I am sharing the honor by mistake.
