### ISSUE TITLE
from bert import modeling, optimization not supported

### ISSUE THREAD

**Issue by fgroesselfs** [kpe/bert-for-tf2#71]
Original BERT from Google Research (https://github.com/google-research/bert) has modeling, optimization, run_pretraining. Is this not supported in bert-for-tf2?

**Comment by kpe** [comment]
the original google-research/bert has been coded for tensorflow 1 (which is the reason why bert-for-tf2 exists). Currently there is no example of how to do pre-training with bert-for-tf2.
